/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SHELL_H_RPCGEN
#define _SHELL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Data {
	char cmd[100];
	int max;
};
typedef struct Data Data;

#define SHELL_PROG 13
#define SHELL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_OUTPUT 1
extern  Data * get_output_1(Data *, CLIENT *);
extern  Data * get_output_1_svc(Data *, struct svc_req *);
extern int shell_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_OUTPUT 1
extern  Data * get_output_1();
extern  Data * get_output_1_svc();
extern int shell_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Data (XDR *, Data*);

#else /* K&R C */
extern bool_t xdr_Data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SHELL_H_RPCGEN */
