/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _WHO_H_RPCGEN
#define _WHO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Data {
	char users[100];
};
typedef struct Data Data;

#define WHO_PROG 13
#define WHO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_USERS 1
extern  Data * get_users_1(void *, CLIENT *);
extern  Data * get_users_1_svc(void *, struct svc_req *);
extern int who_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_USERS 1
extern  Data * get_users_1();
extern  Data * get_users_1_svc();
extern int who_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Data (XDR *, Data*);

#else /* K&R C */
extern bool_t xdr_Data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_WHO_H_RPCGEN */
