/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "who.h"

bool_t
xdr_Data (XDR *xdrs, Data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->users, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
