/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "prime.h"

bool_t
xdr_Data (XDR *xdrs, Data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	return TRUE;
}
