/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRIME_H_RPCGEN
#define _PRIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Data {
	char name[32];
	int n;
};
typedef struct Data Data;

#define PRIME_PROG 12
#define PRIME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_PRIME 1
extern  int * get_prime_1(Data *, CLIENT *);
extern  int * get_prime_1_svc(Data *, struct svc_req *);
extern int prime_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_PRIME 1
extern  int * get_prime_1();
extern  int * get_prime_1_svc();
extern int prime_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Data (XDR *, Data*);

#else /* K&R C */
extern bool_t xdr_Data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRIME_H_RPCGEN */
