/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARB_H_RPCGEN
#define _ARB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define ARB_PROG 15
#define ARB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INSERT 1
extern  int * insert_1(int *, CLIENT *);
extern  int * insert_1_svc(int *, struct svc_req *);
#define DISPLAY 2
extern  int * display_1(void *, CLIENT *);
extern  int * display_1_svc(void *, struct svc_req *);
extern int arb_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INSERT 1
extern  int * insert_1();
extern  int * insert_1_svc();
#define DISPLAY 2
extern  int * display_1();
extern  int * display_1_svc();
extern int arb_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARB_H_RPCGEN */
