/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOAD_H_RPCGEN
#define _LOAD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define LOAD_PROG 123456789
#define LOAD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_LOAD 1
extern  double * get_load_1(void *, CLIENT *);
extern  double * get_load_1_svc(void *, struct svc_req *);
extern int load_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_LOAD 1
extern  double * get_load_1();
extern  double * get_load_1_svc();
extern int load_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOAD_H_RPCGEN */
