cmd_/home/mihai/SO2/lab02-tasks/4-multi-mod/mod2.o := gcc -Wp,-MD,/home/mihai/SO2/lab02-tasks/4-multi-mod/.mod2.o.d  -nostdinc -isystem /usr/lib/gcc/i686-linux-gnu/4.6/include -I/home/mihai/linux-3.13/arch/x86/include -Iarch/x86/include/generated  -Iinclude -I/home/mihai/linux-3.13/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/home/mihai/linux-3.13/include/uapi -Iinclude/generated/uapi -include /home/mihai/linux-3.13/include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m32 -msoft-float -mregparm=3 -freg-struct-return -mno-mmx -mno-sse -fno-pic -mpreferred-stack-boundary=2 -march=i686 -maccumulate-outgoing-args -Wa,-mtune=generic32 -ffreestanding -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=2048 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(mod2)"  -D"KBUILD_MODNAME=KBUILD_STR(supermodul)" -c -o /home/mihai/SO2/lab02-tasks/4-multi-mod/mod2.o /home/mihai/SO2/lab02-tasks/4-multi-mod/mod2.c

source_/home/mihai/SO2/lab02-tasks/4-multi-mod/mod2.o := /home/mihai/SO2/lab02-tasks/4-multi-mod/mod2.c

deps_/home/mihai/SO2/lab02-tasks/4-multi-mod/mod2.o := \

/home/mihai/SO2/lab02-tasks/4-multi-mod/mod2.o: $(deps_/home/mihai/SO2/lab02-tasks/4-multi-mod/mod2.o)

$(deps_/home/mihai/SO2/lab02-tasks/4-multi-mod/mod2.o):
